# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.Bar do
  @moduledoc """
  The bars API returns aggregate historical data for the requested securities. 
  """

  @derive Jason.Encoder
  defstruct [
    :t,
    :x,
    :o,
    :h,
    :l,
    :c,
    :v,
    :n,
    :vw
  ]

  @type t :: %__MODULE__{
    :t => DateTime.t,
    :x => String.t | nil,
    :o => float(),
    :h => float(),
    :l => float(),
    :c => float(),
    :v => float(),
    :n => integer() | nil,
    :vw => float() | nil
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:t, :datetime, nil)
  end
end

