# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.BarsResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :bars,
    :symbol,
    :next_page_token
  ]

  @type t :: %__MODULE__{
    :bars => [MarketDataAPI.Model.Bar.t],
    :symbol => String.t,
    :next_page_token => String.t | nil
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:bars, :list, MarketDataAPI.Model.Bar)
  end
end

