# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.GetNewsResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :news,
    :next_page_token
  ]

  @type t :: %__MODULE__{
    :news => [MarketDataAPI.Model.News.t] | nil,
    :next_page_token => String.t | nil
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:news, :list, MarketDataAPI.Model.News)
  end
end

