# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.LatestMultiXbboResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :xbbos
  ]

  @type t :: %__MODULE__{
    :xbbos => %{optional(String.t) => MarketDataAPI.Model.Xbbo.t}
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:xbbos, :map, MarketDataAPI.Model.Xbbo)
  end
end

