# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.LatestMultiTradesResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :trades
  ]

  @type t :: %__MODULE__{
    :trades => %{optional(String.t) => MarketDataAPI.Model.Trade.t}
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:trades, :map, MarketDataAPI.Model.Trade)
  end
end

