# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.LatestQuoteResponse do
  @moduledoc """
  A model representing the result of hitting the Latest Quote api.  Represents a single Quote that should be the latest quote data for a given ticker symbol
  """

  @derive Jason.Encoder
  defstruct [
    :quote,
    :symbol
  ]

  @type t :: %__MODULE__{
    :quote => MarketDataAPI.Model.Quote.t,
    :symbol => String.t
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:quote, :struct, MarketDataAPI.Model.Quote)
  end
end

