# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.LatestBarResponse do
  @moduledoc """
  A model representing the result of hitting one of the Latest Bar api endpoints.  Represents a single Bar that should be the latest Bar data for a given ticker symbol
  """

  @derive Jason.Encoder
  defstruct [
    :symbol,
    :bar
  ]

  @type t :: %__MODULE__{
    :symbol => String.t,
    :bar => MarketDataAPI.Model.Bar.t
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:bar, :struct, MarketDataAPI.Model.Bar)
  end
end

