# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.LatestTradeResponse do
  @moduledoc """
  A model representing the result of hitting the Latest Trade api.  Represents a single Trade that should be the latest trade data for a given ticker symbol
  """

  @derive Jason.Encoder
  defstruct [
    :trade,
    :symbol
  ]

  @type t :: %__MODULE__{
    :trade => MarketDataAPI.Model.Trade.t | nil,
    :symbol => String.t
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:trade, :struct, MarketDataAPI.Model.Trade)
  end
end

