# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.MarketMoversResponse do
  @moduledoc """
  Contains list of market movers 
  """

  @derive Jason.Encoder
  defstruct [
    :gainers,
    :losers,
    :market_type,
    :last_updated
  ]

  @type t :: %__MODULE__{
    :gainers => [MarketDataAPI.Model.MarketMoverAsset.t],
    :losers => [MarketDataAPI.Model.MarketMoverAsset.t],
    :market_type => String.t,
    :last_updated => String.t
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:gainers, :list, MarketDataAPI.Model.MarketMoverAsset)
     |> Deserializer.deserialize(:losers, :list, MarketDataAPI.Model.MarketMoverAsset)
  end
end

