# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.News do
  @moduledoc """
  Model representing a news article from the Alpaca Market Data API
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :headline,
    :author,
    :created_at,
    :updated_at,
    :summary,
    :content,
    :url,
    :images,
    :symbols,
    :source
  ]

  @type t :: %__MODULE__{
    :id => integer(),
    :headline => String.t,
    :author => String.t,
    :created_at => DateTime.t,
    :updated_at => DateTime.t,
    :summary => String.t,
    :content => String.t,
    :url => String.t | nil,
    :images => [MarketDataAPI.Model.NewsImage.t],
    :symbols => [String.t],
    :source => String.t
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:images, :list, MarketDataAPI.Model.NewsImage)
  end
end

