# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.NewsImage do
  @moduledoc """
  A model representing images for news article. simply a url to the image along with a size parameter suggesting the display size of the image
  """

  @derive Jason.Encoder
  defstruct [
    :size,
    :url
  ]

  @type t :: %__MODULE__{
    :size => String.t,
    :url => String.t
  }

  def decode(value) do
    value
  end
end

