# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.QuotesResponse do
  @moduledoc """
  The Quotes API provides NBBO quotes for a given ticker symbol at a specified date. 
  """

  @derive Jason.Encoder
  defstruct [
    :quotes,
    :symbol,
    :next_page_token
  ]

  @type t :: %__MODULE__{
    :quotes => [MarketDataAPI.Model.Quote.t] | nil,
    :symbol => String.t,
    :next_page_token => String.t | nil
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:quotes, :list, MarketDataAPI.Model.Quote)
  end
end

