# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.Snapshot do
  @moduledoc """
  The Snapshot API for one ticker provides the latest trade, latest quote, minute bar daily bar and previous daily bar data for a given ticker symbol. 
  """

  @derive Jason.Encoder
  defstruct [
    :latestTrade,
    :latestQuote,
    :minuteBar,
    :dailyBar,
    :prevDailyBar
  ]

  @type t :: %__MODULE__{
    :latestTrade => MarketDataAPI.Model.Trade.t | nil,
    :latestQuote => MarketDataAPI.Model.Quote.t | nil,
    :minuteBar => MarketDataAPI.Model.Bar.t | nil,
    :dailyBar => MarketDataAPI.Model.Bar.t | nil,
    :prevDailyBar => MarketDataAPI.Model.Bar.t | nil
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:latestTrade, :struct, MarketDataAPI.Model.Trade)
     |> Deserializer.deserialize(:latestQuote, :struct, MarketDataAPI.Model.Quote)
     |> Deserializer.deserialize(:minuteBar, :struct, MarketDataAPI.Model.Bar)
     |> Deserializer.deserialize(:dailyBar, :struct, MarketDataAPI.Model.Bar)
     |> Deserializer.deserialize(:prevDailyBar, :struct, MarketDataAPI.Model.Bar)
  end
end

