# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.TradesResponse do
  @moduledoc """
  A model representing the result of hitting the Trades api.  Represents multiple Trades for a single symbol with support for paging.
  """

  @derive Jason.Encoder
  defstruct [
    :trades,
    :symbol,
    :next_page_token
  ]

  @type t :: %__MODULE__{
    :trades => [MarketDataAPI.Model.Trade.t],
    :symbol => String.t,
    :next_page_token => String.t | nil
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:trades, :list, MarketDataAPI.Model.Trade)
  end
end

