# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.Trade do
  @moduledoc """
  A model representing a trade
  """

  @derive Jason.Encoder
  defstruct [
    :t,
    :x,
    :p,
    :s,
    :c,
    :i,
    :z,
    :tks
  ]

  @type t :: %__MODULE__{
    :t => DateTime.t | nil,
    :x => String.t,
    :p => float() | nil,
    :s => float() | nil,
    :c => [String.t] | nil,
    :i => integer(),
    :z => String.t | nil,
    :tks => String.t | nil
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:t, :datetime, nil)
  end
end

