# NOTE: This file is auto generated by OpenAPI Generator 7.6.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MarketDataAPI.Model.Xbbo do
  @moduledoc """
  XBBO or Cross Best Bid and Offer represents the Best Bid and Offer for an exchange
  """

  @derive Jason.Encoder
  defstruct [
    :t,
    :ax,
    :ap,
    :as,
    :bx,
    :bp,
    :bs
  ]

  @type t :: %__MODULE__{
    :t => DateTime.t,
    :ax => String.t,
    :ap => float(),
    :as => float(),
    :bx => String.t,
    :bp => float(),
    :bs => float()
  }

  alias MarketDataAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:t, :datetime, nil)
  end
end

